nameOverride: ""
fullnameOverride: ""

image:
  repository: "itzg/mc-monitor"
  tag: "latest"
  pullPolicy: "IfNotPresent"

restartPolicy: Always

nodeSelector: {}

tolerations: {}

affinity: {}

resources: {}

# The securityContext of the pod.
# ref: https://kubernetes.io/docs/concepts/policy/security-context/ for more.
podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

# The securityContext of the container.
# ref: https://kubernetes.io/docs/concepts/policy/security-context/ for more.
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true

# Configuration for the Minecraft metrics exporter.
config:
  servers: []
  bedrockServers: []
  port: 8080
  timeout: "1m0s"
