apiVersion: v1
kind: Service
metadata:
  labels: {{- include "minecraft-proxy.labels" . | nindent 4 }}
  name: {{ include "minecraft-proxy.fullname" . }}
spec:
  ports:
  - name: http
    port: 25577
    protocol: TCP
    targetPort: http
  selector: {{- include "minecraft-proxy.selectorLabels" . | nindent 4 }}
  type: ClusterIP
