{{- $source := .Values.server.assets.source -}}

{{- if $source.curseforgeApiKey }}
apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "minecraft.common.labels" . | nindent 4 }}
  name: {{ include "minecraft.common.curseforgeSecretName" . }}
data:
  {{ include "minecraft.common.curseforgeSecretKey" . }}: {{ $source.curseforgeApiKey | b64enc }}
{{- end }}
