{{- $rcon := .Values.rcon -}}

{{- if eq ( include "minecraft.common.isRconEnabled" . ) "true" }}
apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "minecraft.common.labels" . | nindent 4 }}
  name: {{ include "minecraft.common.rconSecretName" . }}
data:
  {{ include "minecraft.common.rconSecretKey" . }}: {{ default ( randBytes 12 ) $rcon.password | b64enc }}
{{- end }}
