{{- $config := .Values.backup.config -}}

{{- if $config.resticPassword }}
apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "minecraft.common.labels" . | nindent 4 }}
  name: {{ include "minecraft.common.resticSecretName" . }}
data:
  {{ include "minecraft.common.resticSecretKey" . }}: {{ $config.resticPassword | b64enc }}
{{- end }}
